# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
warnings_are_errors: false
cache: packages;
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "vignettes/paper.html"
  skip_cleanup: true
  on:
    tags: true
    branch: master
